### ISSUE TITLE
Be able to handle System.Collections.Generic and System.Collections.ObjectModel et.c.

### ISSUE THREAD

**Issue by wallymathieu** [fsprojects/FSharpPlus#109]
### Description

Would it be useful to be able to use existing operators and methods also for .net collection classes. For instance [IList<>](https://msdn.microsoft.com/en-us/library/system.collections.ilist(v=vs.110).aspx) and others?

- ICollection<>, IList<>, List<> 
- IReadonlyCollection<>

Or is this less useful due to the fact that you usually expose concrete implementation when dealing with c# implemented classes?

**Comment by gusty** [comment]
At the moment the only abstraction that recognize most kind of collections is ``Foldable`` because the generic function ``ofSeq`` has a bunch of overloads.

We could in theory extend them to other abstractions, like Functor, Applicative or Monad but we have to make sure we use interfaces that allow us to clone the collections.

**Comment by gusty** [comment]
While working in Fleece I just run into a situation where I need `tryItem` to work for `IReadOnlyDictionary<_,_>`  this will allow me to replace:


    /// Gets a value from a Json object
    let inline jget (o: IReadOnlyDictionary<string, JsonValue>) key =
        match o.TryGetValue key with
        | true, value -> ofJson value
        | _ -> Failure ("Key '" + key + "' not found in " + JObject(o).ToString())

    /// Tries to get a value from a Json object.
    /// Returns None if key is not present in the object.
    let inline jgetopt (o: IReadOnlyDictionary<string, JsonValue>) key =
        match o.TryGetValue key with
        | true, value -> ofJson value |> map Some
        | _ -> Success None

with

    /// Gets a value from a Json object
    let inline jget (o: Collections.ObjectModel.ReadOnlyDictionary<string, JsonValue>) key =
        tryItem key o |> option ofJson (Failure ("Key '" + key + "' not found in " + string (JObject(o))))

    /// Tries to get a value from a Json object.
    /// Returns None if key is not present in the object.
    let inline jgetopt (o: IReadOnlyDictionary<string, JsonValue>) key = traverse ofJson (tryItem key o)


but found out that it already works for `ReadOnlyDictionary<_,_>` !

This seems to be because ReadOnlyDictionary implements `IDictionary<_,_>` which is the Default2 overload.

So, in order to make it work for ``IReadOnlyDictionary<_,_>`` there 2 options:

1) Add an overload for it:

    static member        TryItem (x: IReadOnlyDictionary<'K,'T>, k        , [<Optional>]_impl: Default3) = tupleToOption (x.TryGetValue k)                                  : 'T option

2) Replace Default2 overload with

    static member inline TryItem (x: '``Indexable<'T>``, k        , [<Optional>]_impl: Default2) =
                    let mutable r = Unchecked.defaultof< ^R>
                    if (^``Indexable<'T>``: (member TryGetValue: _ * _ -> _) (x, k, &r)) then Some r else None

Option 2 has the benefit that is more generic and it will work with anything that follow that signature, at the same time this could be undesired if there is a type that has that signature but it's not an indexable. So the question maps into if there such type or is it likely to find such type?

**Comment by wallymathieu** [comment]
Is there any compiler performance impact to use 2)? I don't think that I've seen that many custom TryGetValue in the wild, though a quick search of github turned up: https://github.com/JohnJosuaPaderon/Sorschia.NET/blob/20cddb6025a0935e8babec3339f76591e4c94887/Sorschia.Data/IDbDataReaderConverterProperty.cs

**Comment by wallymathieu** [comment]
I agree, I think option 2 seems like the nicer option.

**Comment by wallymathieu** [comment]
I also noticed the need for the need for indexer when dealing with lenses for fleece.

**Comment by gusty** [comment]
Yes, actually Indexed was motivated by Lens.

**Comment by gusty** [comment]
I would be nice to compile a todo list of what needs to be done in order to complete this issue. Or put it in another way: what needs to be addressed.

**Comment by wallymathieu** [comment]
#115 Is an attempt to start answering what needs to be added

**Comment by wallymathieu** [comment]
Is there anything else needed for this issue? Or should we close it @gusty ?

**Comment by gusty** [comment]
I think we'll never add all methods of all ReadOnly stuff because it's a lot of work and it's not justified given that probably nobody will benefit of all of them.

So, regarding this issue we can close it, which doesn't prevent to continue submitting (and accepting) PRs for ReadOnly stuff.

Otherwise this issue will be kept open indefinitely.

**Comment by wallymathieu** [comment]
I'm closing it. I don't see the value of having this issue up indefinitely.
