### ISSUE TITLE
Weird try/with/finally behavior in monad CE

### ISSUE THREAD

**Issue by cmeeren** [fsprojects/FSharpPlus#137]
It doesn't seem that `try` catches exceptions. Repro (using xUnit and Unquote):

```f#
/// Helper type for simulating side effects.
type Trigger() =
  let mutable isTriggered = false
  member __.Trigger () = isTriggered <- true
  member __.Triggered = isTriggered

[<Fact>]
let ``behavior of try-with-finally when thrown`` () =
  let tTry = Trigger()
  let tCatch = Trigger()
  let tFinally = Trigger()

  let result = monad {
    try
      try
        failwith ""
        tTry.Trigger()
      with _ -> tCatch.Trigger()
    finally tFinally.Trigger()
  }
  test <@ result = Ok () @>
  test <@ not tTry.Triggered @>
  test <@ tCatch.Triggered @>
  test <@ tFinally.Triggered @>
```

None of the unquote tests are checked, because the exception is not caught, but they do describe what should happen if the exception is caught.

**Comment by gusty** [comment]
Interesting.

Obviously the reason is again because `Result` is not really lazy, using a strict workflow is the right thing.

Now this is another indication that mixing workflows (and autosensing them) is not that great.

We should definitely think about it, if we revert this decision we can release a new major version of the library, or we can deprecate existing workflows and create new one, which wouldn't require a new major release.

**Comment by wallymathieu** [comment]
Can we close this issue in favor of #140 ?

**Comment by cmeeren** [comment]
Sure!
