### ISSUE TITLE
Union function performance

### ISSUE THREAD

**Issue by gusty** [fsprojects/FSharpPlus#144]
We need to know if what we have right now is the most efficient way to compute the unions.

Here's the relevant code: https://github.com/fsprojects/FSharpPlus/blob/master/src/FSharpPlus/Extensions.fs#L332-L508

There other ways to implement it, it would be nice to have a PR that suggest another way and proves that it's more efficient.

**Comment by gusty** [comment]
Assigned to @pnobre

**Comment by pnobre** [comment]
Union could also be implemented System.Linq.Enumerable.Union (slightly faster than current impl).
Given
`let d1 = Map.ofSeq [for f in 1..1000000 do yield (f, f.ToString())]
 let d2 = Map.ofSeq [for f in 1..1000000 do if f % 2 = 0 then yield (f, f.ToString())]`

Current implementation results in
`Real: 00:00:01.300, CPU: 00:00:01.296, GC gen0: 63, gen1: 15, gen2: 0`

and Enumerable.Union results in 
`Real: 00:00:00.962, CPU: 00:00:00.937, GC gen0: 35, gen1: 1, gen2: 0`

Less time, less GC. However it could break compatibility due to the combiner function as the implementation using linq should be 
`d1.Union(d2).ToDictionary((fun x -> x.Key), (fun y -> y.Value))`

**Comment by pnobre** [comment]
Submitted #146

**Comment by gusty** [comment]
I would say, if you can internalize those details, in order to keep compatibility, there's no reason not to merge your PR.

**Comment by gusty** [comment]
Closed as per #146
