### ISSUE TITLE
Not an issue but a question / request ?

### ISSUE THREAD

**Issue by kunjee17** [fsprojects/FSharpPlus#152]
I really like you work. Thanks for all these hard work. 

Is it ok if I steal your work ? 

I like to port FSharpplus to Fable. Most of the F# code is valid for Fable as well but sometimes few system related call needed to be removed. And It might require some trimming. I normally trim down to bare minimum and then add things back again as and when it is required. 

Is it OK if I still some of your work, with name as well for Fable? I will put everything open source so it would be useful to everyone else. And if you like to do the honor (keep the project under FSharpplus name and company - maintainers  ) I am more than happy to help there as well. Means whatever works for you all.

**Comment by wallymathieu** [comment]
Since most of FSharpPlus is pure, wouldn't make more sense to do a PR so that the library can be tested against Fable? I don't think I've seen any system related calls in the FSharpPlus code base.

**Comment by wallymathieu** [comment]
There is an answer related to Fable here : https://github.com/fsprojects/FSharpPlus/issues/121#issuecomment-408124993
So to answer your question: you are more than welcome to help out here :smiley: The repository is hosted under [fsprojects](https://github.com/fsprojects) in order to attract help from the greater f# community.

**Comment by kunjee17** [comment]
@wallymathieu Thanks mate. I surely give it a try and will give PR to make it more Fable friendly. I am closing the issue as of now. Thanks again.
