### ISSUE TITLE
Implement tee/tap for functors?

### ISSUE THREAD

**Issue by cmeeren** [fsprojects/FSharpPlus#214]
The generic `iter` takes a functor and an action to perform, and returns `unit`.

I'd like a similar function that passes through the functor, i.e. performs a `unit`-returning action and then returns the original input (for further chaining). As I understand it, this is typically called `tee` or `tap`. Could this be added?

Le me know if this is unclear and I should provide more details.

**Comment by gusty** [comment]
I think `tee` also called `tap` is a function with signature  `('T->unit) -> 'T -> 'T`.

So, it's not restricted to functors, but you could achieve the desired effect by doing `map (tee f) functor`. 

And yes, it's something that should be added to this library. The first question is which name it should be?

**Comment by cmeeren** [comment]
I have always called it `tee`, but I don't really care whether it's called `tee` or `tap`.

Perhaps one could also define `ftee` or `ftap` as `map >> tee`, so have a similar function that works with inner functor values? Though AFAIK that would re-"construct" the functor, and a custom implementation that simply passes the whole functor through would be more effective.

**Comment by wallymathieu** [comment]
I've used `entity.Tap(c=>...)` in c#. I think in more functional f#y code I've seen some use of `tee`. Haskell seems to have both and use different semantics for them.

**Comment by wallymathieu** [comment]
I think https://leanpub.com/combinators used Tap

**Comment by gusty** [comment]
@wallymathieu I think `tap` it's also used in Scala.

@cmeeren well, the composition is backwards `map << tee` but you're right in that it won't be efficient.

An easy alternative is `let inline ftee f x = iter f x; x`

**Comment by cmeeren** [comment]
Yep. Would be great to have that built-in, because defining such generic functions in our own projects causes compilation times and Intellisense lag to skyrocket.

**Comment by cmeeren** [comment]
A related thing to consider is an `rftee` or whatever you'd call it, that works on the "other" side of bifunctors (e.g. `Result.Error` or `Choice2Of2`).

**Comment by cannorin** [comment]
```fsharp
let tee f x = f x; x

xs |> tee (iter (fun x -> ..))
```

?

**Comment by gusty** [comment]
@cannorin I think that snippet demonstrate that maybe `ftee` (or whichever name it gets) is not very justified, because it saves you only a few keystrokes. So maybe it doesn't worth poluting the lib with functions like this.

@cmeeren  the problem is that `Result<'t,unit>` is not a bifunctor as you can't map any other type over `unit`.

I think we all agree tee / tap would make a good addition, as said before, we just have to agree on the name.

I personally like a bit more `tap`. Please case your vote ;)

**Comment by wallymathieu** [comment]
My personal preference is tap

**Comment by cmeeren** [comment]
> @cmeeren the problem is that `Result<'t,unit>` is not a bifunctor as you can't map any other type over `unit`.

I'm no CT expert. Could you explain why `Result<'t, unit>` poses a problem (and for what)? I don't get it. `unit` is a type like any other, right?

**Comment by gusty** [comment]
@cmeeren Sorry about my poor explanation, here's a (hopefully) better attempt.

`Result<'T,'U>` (read 'T and 'U as **variable** types) is a bifunctor, as I can map a ('T -> 'A) and a ('U -> 'B) and get a "bimapped"version of it.

Now, `Result<'T,unit>`  (unit or another **fixed** type) is not, because I can't map any function to the right side, I could only map a `unit->unit` function, otherwise I would end up with a different type.

**Comment by gusty** [comment]
Although this issue was closed years ago at https://github.com/fsprojects/FSharpPlus/commit/4bb14278e08632d65ca2351829e0071260339d4f there was no explanation of how that commit solves this issue by simply adding the regular (non hypergeneric) `tap` function. Later on the `(|-)` operator was added which is like the function but with flipped arguments.

But the unanswered question here is how does these addition solve the request of tee/tap for functors. It might not be obvious, so here is a sample code:

Let's pretend we had `Result.tee` and so on for each functor

```
    |> Result.tee printValue
```

but it can be written

```
    |- Result.iter printValue
```

Moreover, if we want to tap on the error side, we would need a special function `Result.teeError` but we can do:

```
    |- Result.iterError printValue
```




So, as long as we have iter available we can combine it with `tap` function (or operator) in order to tap inside a functor context.

Note: to please generic operator lovers, a possible enhancement would be adding the `||-` operator ;)
