### ISSUE TITLE
Question: understanding generic functions...

### ISSUE THREAD

**Issue by adz** [fsprojects/FSharpPlus#219]
I've started happily using ResultT as a Monad Transformer and it is working perfectly well. However, I wanted to write a generic `mapError` function to use with it, since I prefer it to `</catch/> (throw << myFunc)`.

This worked for me:
```
let mapError f (ResultT asyncResult) =
    async {
        let! result = asyncResult
        return Result.mapError f result
    }
    |> ResultT
```

It's type is:
```val mapError: 
   f: 'a -> 'b ->
    : ResultT<Async<Result<'c,'a>>> 
   -> ResultT<Async<Result<'c,'b>>>
```

However, if I use any FSharpPlus functions, it seems to 'specialise' to the calling code...

As in:
```let mapError f r =
     r </catch/> (f >> throw) 
```

or from Bifunctor
```
let mapError = second
```
gives something like this
```
Type constraint mismatch when applying the default type 'obj' for a type inference variable. internal error: Exception of type 'FSharp.Compiler.ConstraintSolver+LocallyAbortOperationThatFailsToResolveOverload' was thrown. Consider adding further type constraintsF# Compiler(71)
```

Can you help me understand what's going on?
Is there a way to reuse FSharpPlus functions from my own functions?

**Comment by gusty** [comment]
I think you're missing the fact that generic functions F# have to be declared as inline function, for instance this won't work for sure:

    let mapError = second

Since `second` is a generic function, you can't assign it as a value.
Try instead:

    let inline mapError a b = second a b

Finally it worths noting that SRTP resolution in F# is unfortunately not perfect currently. If you define generic functions on your own at some point you might find some limitations.

The aim of this library is more towards using the provided functions that creating your owns, given these limitations, but sometimes you can go quite far is F# type systems allows you.

If this is not the case and you really feel that your generic function is a useful addition you can propose to add it. 

I hope this helps. Otherwise if you have a specific code that doesn't work please post it here.

**Comment by adz** [comment]
Thanks. I'll try that out.

I'll think about proposing functions...

Can you point to what the limitations are?

Also, is there a chat or slack where these kinds of questions might be better suited? Sorry if this is wrong place! I was thinking a fsharpplus channel on slack if there wasn't?

________________________________

**Comment by gusty** [comment]
I can't point you to the limitations as most of them are problems (bugs) in the F# compiler.

But as I said, just go ahead, sometimes you can go pretty far defining generic functions, just do some experiment.

Regarding questions, I would advise to use the #code or #fp_theory channels of the FSSF slack.

I usually keep an eye on those channels and you can mention me, so I get notified.
