### ISSUE TITLE
Trouble using liftAsync

### ISSUE THREAD

**Issue by adz** [fsprojects/FSharpPlus#224]
### Description

When using liftAsync with a ResultT<Async<Result<_,_>>> in one case I am getting a compile error. Types appear to be line up, and things work when using direct types.

### Repro steps

See this repo, with issue, and description:
https://github.com/adz/test_fsharp_plus_liftAsync

### Expected behavior

I expected it to compile, but it doesn't without explicit types.

### Known workarounds

Annotate types on `liftAsync`:
```fsharp
 (liftAsync : Async<HttpResponse> -> ResultT<Async<Result<HttpResponse,ExchangeError>>>)
```

Use explicit functions:
```fsharp
|> Async.map Ok |> ResultT
```

### Related information 

dotnetcore 3.1 or 3.0
other versions in repo

**Comment by gusty** [comment]
Thanks for the report.

This is a limitation of F# type inference. There's no much we can do in this lib to improve it.

For your information `liftAsync` is a very generic function as it lift the async thorough a layer of n monads, that's why type inference is pushed to the limits.

I would like to improve the compiler, to make it smarter as I think it should be possible to resolve most of these cases by changing a bit the logic in the type inference.

At the same time I think, we should document Monad transformers, explaining this kind of limitations and some give some workarounds.

Also consider as workaround, using the `lift` function, or the less generic `ResultT.Lift` method.

I will close this issue, as the solution has to be implemented in the compiler, but we can keep discussing here some workarounds.

**Comment by adz** [comment]
Thanks. It was a frustrating experience, so I'd like to understand these limitations. It seems arbitrary and kind of magic to me when it can't work...

Plan was to wrap csharp lib calls to return a resultT and annotate types to help inference. However that didn't seem to help here. I'll check that again... Would love to help with documentation.

With regard to using specific function on ResultT how would this work for, say, if wrapped in another layer?

**Comment by gusty** [comment]
If it's wrapped in another layer you'll have to lift to one layer, then to another.

In any case, be aware that if you use more than  2 layers you'll start to experience some flaws of Monad transformers like:

 - Big type signature
 - Poor compile times
 - Type inference problems

Although the last 2 are due to F# compiler limitations.

I think, when you end up with more than 2 layers you can start evaluating other solutions like the update monad (we can add it here), or doing a custom type.

Although it's technically possible to layer more than 2 monads, you can try it and see if it makes your life easier or not.

**Comment by gusty** [comment]
I was trying to find a small/standalone/script-only repro, but failed.

Looks like the problem comes from calling the function in FSharp.Data becuase I tried to mimic the datatype and works.

An easy and typical workaround is to add at the very end the annotation `  : ResultT<_>`
