### ISSUE TITLE
Generic put doesn't work in Monad Transformers

### ISSUE THREAD

**Issue by gusty** [fsprojects/FSharpPlus#23]
The following code doesn't compile:

    let initialState = -1
    let x = put initialState : ListT<State<int, unit list>>
    let y = put initialState : ErrorT<State<int, Choice<unit,string>>>

**UPDATE**

After the re-re introduction of <code>liftM</code> it compiles again, but it could generate more efficient code using <code>map</code>.

**Comment by gmpl** [comment]
This is a consequence of another issue: type inference fails when <code>liftM</code> is implemented as <code>map</code>.
At the same time that issue is a consequence of an F# issue, since after doing some tests like this:

    static member inline Lift (x:'``Monad<'T>``) = 
      if false then ListT (x >>= (result << List.singleton)) else ListT (map List.singleton x)

looks like type inference fails depending on the execution path (switch to <code>true</code> and it compiles fine.

This is clearly an F# bug, compilation shouldn't fail depending on the execution path.

**TODO**:

- Find a minimal repro
- Report it as a bug in the F# compiler project, then reference this issue and close it
- If no one there is interested in solving it, try to fix it

In the meantime the best compromise is to re-re-introduce <code>liftM</code> this might lead to a slightly less optimised code for those cases where the <code>map</code> operation is more efficient but at least will work which is a minimal requirement.

If more efficient code is required it's always possible to replace the generic code with a more specific implementation, in the repro it will be:

    let x = ListT (map List.singleton (State.put initialState))

**Comment by gusty** [comment]
Done here: https://github.com/dotnet/fsharp/issues/7384

**Comment by gusty** [comment]
Reopening as this is still an issue
