### ISSUE TITLE
Contribute to FSharpPlus

### ISSUE THREAD

**Issue by ivan-vargas** [fsprojects/FSharpPlus#339]
I would like to contribute to this project. I was looking up in the documentation to see if there was some kind of established process to do so, but all I could find was this

> The project is hosted on GitHub where you can report issues, fork the project and submit pull requests.
> 
> If you're adding a new public API, please also consider adding documentation. You might also want to read the library design notes to understand how it works.

What should I do to contribute?

Thanks

**Comment by wallymathieu** [comment]
The easiest first step is to look into adding documentation around how to use the library.

First step could be to download the source code,

in `./docsrc/content` you will find many documentation files with missing content. An example of adding some more content to documentation pages can be found [here](https://github.com/fsprojects/FSharpPlus/pull/332).

In order to manually build the docs to view how it would be rendered, you can build the project:
```
dotnet restore ./FSharpPlus.sln
dotnet build -c Release ./FSharpPlus.sln
```

then in order to download the nugets needed by the documentation generation you either run:
```
./docsrc/tools/download_nugets.sh
```
or if you are on windows
```ps1
.\docsrc\tools\download_nugets.ps1
```

to build the docs and have them rendered in the `./docs` folder you run the following:
```
dotnet run -c Release --project ./docsrc/tools
```

If you on the other hand want to contribute tests to verify that the functionality works as expected then you can run the tests locally:
```
dotnet test -c Release tests/FSharpPlus.Tests
```
It should also be possible to run these tests in Visual Studio if that is preferred.

**Comment by wallymathieu** [comment]
One of the gotchas right now when cloning the repository is that you want to do:
```
git submodule init
git submodule update
```
if the submodule has not been downloaded already.

**Comment by wallymathieu** [comment]
This is sort of related to the following [pull request](https://github.com/fsprojects/FSharpPlus/pull/253)

**Comment by ivan-vargas** [comment]
Sounds good! I'll take a look and start playing with it.

Much appreciated!
