### ISSUE TITLE
Make Async's "apply" function more applicative

### ISSUE THREAD

**Issue by AlexeyRaga** [fsprojects/FSharpPlus#429]
Currently, `Async.apply` is defined "monadically" (via `Bind`):

```fsharp
let apply f x = async.Bind (f, fun x1 -> async.Bind (x, fun x2 -> async {return x1 x2}))
```

While this implementation works, it doesn't run two input computations in parallel.

Would it make sense to re-define `Async.apply` more "applicatively"? It could look like:

```fsharp
    let apply f x =
        async {
             // start the two asyncs in parallel
            let! fChild = Async.StartChild f  // run in parallel
            let! x' = x
            // wait for the result of the first one
            let! f' = fChild
            return f' x'
        }
```

Then the same technique can be used for `map2`, `map3` and `zip`, so that we get more parallelism while using `Async` computations?

Would you be keen to implement it this way or accept a PR?

**Comment by gusty** [comment]
I think there's a misconception here. Parallel execution doesn't make the applicative async more applicative, it just make it a parallel abstraction, which is not necessarily what Async is.

Apart form that there other techincal issues, see this discussion https://github.com/dotnet/fsharp/discussions/11043

In order to profit from this parallel execution, we can either:

 - Add an explicit function whose names implies parallel execution (`apply` doesn't).
 - Add another type which is basically a wrapper over async with parallel operations, not just `apply` but also `traverse` and `sequence`

The latter approach is captured in this discussion #36

**Comment by AlexeyRaga** [comment]
I don't think that `apply` implies sequential execution either, and I think that an applicative abstraction implies the fact that we cannot rely on the execution order being sequential, but I do take the point.

**Comment by gusty** [comment]
Well, actually the `async` abstraction express just asynchronous computations, independent of the execution model. The idea is that when you execute the abstraction you decide how. There some interesting details about this on the linked discussion.
