### ISSUE TITLE
Generic monad functions with SeqT

### ISSUE THREAD

**Issue by harrisse** [fsprojects/FSharpPlus#472]
### Repro

```
let test_b : SeqT<ReaderT<Input, State<MenuState, seq<MenuMessage>>>> =
    monad.plus' {
        let! read_fail_a = ask
        let! state_fail_a = get
        
        let! read_fail_b = lift ask
        let! state_fail_b = lift get
        
        let! read_success_c = SeqT.lift ask
        let! state_success_c = SeqT.lift get
        
        return Exit
    }
```

### Actual behavior

c works as expected, but a and b result in the following compilation error:
```
Type constraint mismatch when applying the default type 'obj' for a type inference variable.
No overloads match for method 'op_GreaterGreaterEquals'. 
Known return type: ReaderT<Input,State<MenuState,seq<MenuMessage>>>
Known type parameters: < obj , (seq<seq<MenuMessage>> -> ReaderT<Input,State<MenuState,seq<MenuMessage>>>) >
```

### Expected behavior

I expected to be able to use generic functions like `ask` and `get` with `SeqT` without lifting, but maybe I'm misunderstanding how deep my nested monads are or I've set the wrong type parameters or something like that? Maybe I can't mix side effects and monad.plus?

**Comment by harrisse** [comment]
Actually c) only compiled because I didn't try to consume the results even though intellisense can seemingly detect the types that read_success_c and state_success_c are supposed to be. I'm going to guess this is just a misunderstanding on my end of how to combine Seq and State or that that use case is not supported.

**Comment by harrisse** [comment]
Going to close this for now until I can make a more concrete repro case / better understand SeqT.

**Comment by gusty** [comment]
Just fyi, `SeqT` and `ListT` as they are right now don't provide an interesting effect to the inner monad.

A proper `SeqT` implementation, when combined with `Async` should derive async sequences, similarly a proper `ListT` combined with `Lazy` should automatically derive a lazy list.

I have a `ListT` on [the drafts](https://github.com/fsprojects/FSharpPlus/tree/gusty-listt) since almost 2 years, the problem is that due lack of higher kinds, it requires so many type level equations that the compiler slows down a lot, even for trivial cases.

I hope to be able to solve those issues either with a new version of the compiler and/or with v2 of this library with a significant change in the Invoker mechanism.

**Comment by harrisse** [comment]
Thanks, I am mainly looking for the syntactic sugar to return multiple elements (or ()) which SeqT seems to provide well enough. I was able to solve my problem with `SeqT.lift ask` and ` State.get |> ReaderT.lift |> SeqT.lift` for ask and get respectively.

**Comment by gusty** [comment]
That's fine. One more detail: I see you're using a strict `monad.plus`, by writing `monad.plus'`, but not sure if you read [this section of the docs](http://fsprojects.github.io/FSharpPlus//computation-expressions.html).

There it states:

_For layered monads (monad transformers) the general rule is: the monad is strict unless at least one of its constituent types is lazy, in that case the whole monad becomes lazy._

Following. there is a small snippet that helps you when in doubt whether the monad is strict or not.

In your sample,  both `ReaderT` and `State` are lazy, so even if this version of `SeqT` is strict (unlike the ideal implementation I mentioned in my previous comment), the whole combination should be a lazy one.
