### ISSUE TITLE
Fable 4 support

### ISSUE THREAD

**Issue by OnurGumus** [fsprojects/FSharpPlus#542]
### Description

I can see there are some 
```
#if !FABLE_COMPILER || FABLE_COMPILER_3
```
definitions on FSharp Plus. 
Fable 4 uses 
```FABLE_COMPILER_4``` and FSharp.Data.Lens fails to be found again.

**Comment by wallymathieu** [comment]
See #539

**Comment by wallymathieu** [comment]
@OnurGumus since Fable4 does not support overloading the best we can hope for is for is a subset of F#+ to work. You can try it out with the [CI built version on NuGet](https://www.nuget.org/packages/FSharpPlus/1.4.1-v1.4-CI03263). 

This means that a lot of operators will no longer work in Fable4 even though they did work in Fable3 ...
https://github.com/fsprojects/FSharpPlus/pull/539#issuecomment-1624936577

**Comment by wallymathieu** [comment]
Since we have released F#+ 1.5.0 with the possible support.
