### ISSUE TITLE
Type inference issue with applicative2 

### ISSUE THREAD

**Issue by anpin** [fsprojects/FSharpPlus#548]
### Description

I'm having issue with the compiler type inference when using  `applicative2` to bind together multiple `Task<Validation<'a,'b>>` which I was able to reproduce using following `fsx` 

```
#r "nuget: FSharpPlus"

open FSharpPlus
open FSharpPlus.Data
open System.Threading.Tasks

[<Struct>]
type Errors =
  | UnexpectedError of string

[<Struct>]
type dto = {
  A : string
  B : string
}
[<Struct>]
type TypedTuple<'a,'b> = TypedTuple of struct('a option *  'b option )

let validateA (TypedTuple (did, dto): TypedTuple<string,dto>)   =
  match did with
  | Some _ -> Validation<Errors, _>.Success dto
  | None -> Validation<Errors, _>.Failure (Errors.UnexpectedError "ooops")
  |> Task.FromResult

let validateB (dto: TypedTuple<string,dto>)  = (Errors.UnexpectedError "always fails") |> Validation<_, TypedTuple<string,dto>>.Failure  |> Task.FromResult

let validateBoth dto = applicative2 {
  let! _ = validateA dto
  and! b = validateB dto
  return b
}

printf "%A" (validateBoth (TypedTuple struct(None, Some { A = "a"; B = "b"}))  |> Async.AwaitTask |> Async.RunSynchronously)

```

### Expected behavior

Above code works

### Actual behavior

Compilation fails with: 
```
fp-async-applicative.fsx(28,12): error FS0043: Type constraint mismatch. The type
    'Validation<Errors,TypedTuple<string,dto>>'
is not compatible with type
    'Validation<Errors,'a>'
```

### Known workarounds
I have tried to define concrete types for every variable and function call and it was still complaining. However replacing `Validation<Errors,_>` with  `Validation<string,_>` does the job. 

### Related information 

* Operating system linux
* .NET SDK:  Version:   7.0.302  Commit:    990cf98a27
* F#+ v1.4.1

**Comment by gusty** [comment]
@anpin Sorry for the late reply and thanks for taking the time for reporting this.

It seems to me you have an issue understanding the `Validation` mechanics: the `'Error` type has to be something like a [semigroup](https://fsprojects.github.io/FSharpPlus/abstraction-semigroup.html) that is a type which supports a kind of "self folding" operation, in F#+ that operator should be `static member (+)`.

So, to fix the issue you can define your `Errors` type as `Error` and in turn make `Errors` a list of `Error`:

```
#r "nuget: FSharpPlus"

open FSharpPlus
open FSharpPlus.Data
open System.Threading.Tasks

[<Struct>]
type Error =
  | UnexpectedError of string

type Errors = Error list

[<Struct>]
type dto = {
  A : string
  B : string
}
[<Struct>]
type TypedTuple<'a,'b> = TypedTuple of struct('a option *  'b option )

let validateA (TypedTuple (did, dto): TypedTuple<string,dto>)   =
  match did with
  | Some _ -> Validation<Errors, _>.Success dto
  | None -> Validation<Errors, _>.Failure [Error.UnexpectedError "ooops"]
  |> Task.FromResult
```

Another option could be defining internally your original `Error` as a list and add the `(+)` static member.

When you use a string it just works because `string` is a semigroup and it supports the `+` operation, although the error accumulation will be a bit awkward as it will concatenate all error messages.
